# Generated by Django 3.0.1 on 2019-12-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
