# Generated by Django 3.0.1 on 2019-12-26 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash_pictures', '0002_pin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pin',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pins', to='dash_pictures.Board'),
        ),
    ]
