# Generated by Django 3.0.1 on 2019-12-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_pictures', '0003_auto_20191227_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='deleted',
        ),
    ]
