# Generated by Django 3.0.1 on 2020-01-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash_pictures', '0004_remove_pin_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='dash_pictures.Board'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
